# Generated by Django 4.2.1 on 2023-07-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_alter_blog_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blogtitle',
            field=models.CharField(default='Blog title', max_length=100),
        ),
    ]
